sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest
- pip install codecov
- pip install pytest-cov
script:
- py.test --cov=lang_trans tests/*_u.py
after_success:
- codecov
deploy:
  provider: pypi
  user: kariminf
  password:
    secure: MWZhRrCG5S0vJVj2jBSr2enVMOYvV4dKklfCYT5e9F06o7OGUWgDszG3YWzjfbYT8CYmTTqA0wSo5oGJpj8dr+JGs7s9s9ZD8cqryYViE/P0guK1HY7EOu/icDm6Yoml1e5G/EBOyR8/YJ5fYQT3407lFvjJvDc6oRKFsEvvNQRLCOwS3ATNPbe5urXSI9YmhThJfuLMGa07d89GZAkFsFZK9sNZRbDxv3OwRcltNYlT0ohEryKYxVvOOLPyMyuja38ot+Eph868o84H8eF9/iW4ig+VxT8D9hJO9b0QVlHgnZKTILKTPT0+iE/9T1ES8HpRoh83XhN8toZJDocs7R4Y38AKxIUwkxYJtQ0pV1OAy6kwNYhyMGf72R4vS+HgyYQWFpcJ2UUbSdFhUf1N+nNwzzd6No/+Y3HBSuqoeiZOYXxAEpdGkqY1kaoLhwY2tQt6UbKDKMvvE8mROKlFv/+dLI5w65A5K0wTqeUBkDZ4hlE3zkwkr+bHd6WiKlqXF7x2B/6esEdiSKBLR083CgneTWV/RPpmuZ/8fjlEaUbdAvvGZl31TA5LziB6SZaswnWTGggnDOaayeT5awSpE+Qah/S0XJn2bT++oQipTCLlMZAFDhcPVEcas8ynPXhklXTKpIXm/ly6csH9DLnaLZ1gbqIDHx4/GBR3THAhxxA=
